<?php 
if (!defined('DP_BASE_DIR')) {
	die('You should not access this file directly.');
}
### Copyright (c) 2004, The dotProject Development Team dotproject.net and sf.net/projects/dotproject ###
### All rights reserved. Released under GPL License. For further Information see LICENSE ###

### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE DOTPROJECT INSTALLER ###
### FOR INFORMATION ON MANUAL CONFIGURATION AND FOR DOCUMENTATION SEE ./includes/config-dist.php ###

$dPconfig['dbtype'] = 'mysql';
$dPconfig['dbhost'] = '172.17.0.3:3306';
$dbName=explode("/" , $baseDir);
$dPconfig['dbname'] = 'dotproject_plus';
$dPconfig['dbprefix'] = 'dotp_';
$dPconfig['dbuser'] = 'root';
$dPconfig['dbpass'] = '123456';
$dPconfig['dbpersist'] = false;
$dPconfig['root_dir'] = $baseDir;
$dPconfig['root_dir'] = $baseDir;
if(substr($dPconfig['root_dir'],-1) != '/') $dPconfig['root_dir'] .= '/';
?>